### ISSUE TITLE
不同系统斜杠问题

### ISSUE THREAD

**Issue by Harlber** [xmake-io/xmake-gradle#1]
[XMakeBuildTask.groovy](https://github.com/xmake-io/xmake-gradle/blob/master/gradle-xmake-plugin/src/main/groovy/org/tboox/gradle/XMakeBuildTask.groovy)
```java
File libsDir = new File(taskContext.buildDirectory, "libs/" + taskContext.buildArch)
```
在windows下是否要写成
```java
File libsDir = new File(taskContext.buildDirectory, "libs\\" + taskContext.buildArch)
```

**Comment by waruqi** [comment]
win下我暂时没环境测，这个地方我刚修了，你再试试。。请更新到1.0.7

**Comment by Harlber** [comment]
刚好前几天也写了个小插件，家里电脑是win的，办公室mac，遇到了斜杠问题

**Comment by waruqi** [comment]
恩，这边没win环境测试，你先试试吧，看看win下能否正常使用，按理应该问题不大。
