### ISSUE TITLE
项目依赖的dll没有复制到libs目录下

### ISSUE THREAD

**Issue by vkensou** [xmake-io/xmake-gradle#17]
### Xmake Version

2.9.5

### Operating System Version and Architecture

Windows 10

### Describe Bug

经过这个帖子（https://github.com/xmake-io/xmake/issues/5673 ）里的修改后，libSDL2.so成功复制到了build/xmake/libs下，但没有复制到app/libs下，导致最终的apk里还是没有libSDL2.so。
我在windows下`set_policy("install.strip_packagelibs", false)` 是这样的，不知道linux/mac上可以调用objdump自动检测依赖是不是这样。我猜测应该也一样。

### Expected Behavior

so复制到app/libs，进而打包进apk

### Project Configuration

无

### Additional Information and Error Logs

无

**Comment by waruqi** [comment]
https://github.com/xmake-io/xmake-gradle/pull/14

**Comment by waruqi** [comment]
1.1.9 应该可以了
