### ISSUE TITLE
Request to add RISC-V64

### ISSUE THREAD

**Issue by ifarbod** [xmake-io/xmake-gradle#19]
### Is your feature request related to a problem? Please describe.

https://github.com/xmake-io/xmake/pull/5772

https://github.com/xmake-io/xmake-gradle/blob/bc64df881ccc09a77d89c2847c3c0ee64de73985/gradle-xmake-plugin/src/main/groovy/org/tboox/gradle/XMakePlugin.groovy#L41-L47

### Describe the solution you'd like

Be able to build Risc-V apps with the Xmake gradle plugin.

**Comment by waruqi** [comment]
you can open a pr to add it.
