### ISSUE TITLE
在cmake对应的位置增加xmake相关文件及配置，但没有生成so文件

### ISSUE THREAD

**Issue by hsav20** [xmake-io/xmake-gradle#3]
> 注：如果是`问题报障`或者`特性请求`，请选择对应issues模板，否则一律不回复。

### 描述问题详情
请在这描述你的问题详情。

在cmake生成的demo项目之中，对应的位置增加xmake相关文件及配置，但没有生成so文件，打开页面死掉

--------- beginning of crash
04-26 18:03:08.528 4876-4876/ltd.hsav E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ltd.hsav, PID: 4876
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/ltd.hsav-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]] couldn't find "libnative-lib.so"
        at java.lang.Runtime.loadLibrary(Runtime.java:366)
        at java.lang.System.loadLibrary(System.java:988)
        at ltd.hsav.MainActivity.<clinit>(MainActivity.java:12)
        at java.lang.reflect.Constructor.newInstance(Native Method)
        at java.lang.Class.newInstance(Class.java:1606)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1066)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2226)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
        at android.app.ActivityThread.access$800(ActivityThread.java:151)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
04-26 18:08:08.567 4876-4876/? I/Process: Sending signal. PID: 4876 SIG: 9

**Comment by waruqi** [comment]
启用下 

xmake {
logLevel "verbose"
}

然后贴下完整gradle编译输出

**Comment by hsav20** [comment]
Executing tasks: [:app:assembleDebug] in project D:\ktv\changba\TestC


> Configure project :
Repository https://jcenter.bintray.com/ replaced by http://maven.aliyun.com/nexus/content/groups/public.
Repository https://jcenter.bintray.com/ replaced by http://maven.aliyun.com/nexus/content/groups/public.

> Task :app:preBuild UP-TO-DATE
> Task :app:preDebugBuild UP-TO-DATE
> Task :app:generateDebugBuildConfig UP-TO-DATE
> Task :app:javaPreCompileDebug UP-TO-DATE
> Task :app:compileDebugAidl NO-SOURCE
> Task :app:compileDebugRenderscript NO-SOURCE
> Task :app:mainApkListPersistenceDebug UP-TO-DATE
> Task :app:generateDebugResValues UP-TO-DATE

**Comment by hsav20** [comment]
觉得还没有参考编译

**Comment by hsav20** [comment]
觉得还没有参与编译

**Comment by hsav20** [comment]
就是我在c文件里面随便加了一个错误都没有提示

**Comment by hsav20** [comment]
`附上demo`
[TestC.zip](https://github.com/xmake-io/xmake-gradle/files/4535117/TestC.zip)

**Comment by waruqi** [comment]
你在哪里用的xmake，就在哪里启用xmake插件，你的jni是在app这个module里面的，那么应该在app/build.gradle中应用xmake插件，而不是根build.gradle

app/build.gradle
```
plugins {
    id 'org.tboox.gradle-xmake-plugin' version '1.0.9'
}
apply plugin: 'com.android.application'
```

另外你 add_files()里面的native lib的文件名都不对，得改成：    add_files("native-lib.cpp")

native-lib.cpp里面也有无效的y字符导致编译错误。。

**Comment by hsav20** [comment]
native-lib.cpp里面也有无效的y字符导致编译错误 中故意的，让他错，但没有提示。现在提示

...mdir\core\sandbox\modules\import\core\base\scheduler.lua:47: cannot get program for cxx

**Comment by hsav20** [comment]
Gradle Daemon started in 1 s 298 ms

> Configure project :
Repository https://jcenter.bintray.com/ replaced by http://maven.aliyun.com/nexus/content/groups/public.
Repository https://jcenter.bintray.com/ replaced by http://maven.aliyun.com/nexus/content/groups/public.

> Configure project :app
[xmake/plugin]: activated for project: app

> Task :app:xmakeConfigureForArmv7
>> xmake f -y -v -p android -a armeabi-v7a --buildir=D:\ktv\changba\TestC\app\build\xmake 
checking for the NDK directory ... no
checking for the Android SDK directory ... E:\Android\sdk
checking for the Build Tools Version of Android SDK ... 28.0.3
checking for the g++ ... no
checking for the linker (ld: g++) ... no
checking for the gcc ... no
checking for the linker (ld: gcc) ... no
checking for the clang++ ... no
checking for the linker (ld: clang++) ... no
checking for the clang ... no
checking for the linker (ld: clang) ... no
checking for the shared library linker (sh: g++) ... no
checking for the shared library linker (sh: gcc) ... no
checking for the shared library linker (sh: clang++) ... no
checking for the shared library linker (sh: clang) ... no
configure
{
    arch = armeabi-v7a
    ccache = true
    build_toolver = 28.0.3
    mode = release
    ndk_stdcxx = true
    plat = android
    sdk = E:\Android\sdk
    kind = static
    buildir = ..\..\..\build\xmake
    android_sdk = E:\Android\sdk
    host = windows
}

> Task :app:xmakeBuildForArmv7 FAILED
>> xmake build -v 
configure
{
    arch = armeabi-v7a
    ccache = true
    build_toolver = 28.0.3
    mode = release
    ndk_stdcxx = true
    plat = android
    sdk = E:\Android\sdk
    kind = static
    buildir = ..\..\..\build\xmake
    android_sdk = E:\Android\sdk
    host = windows
}
checking for the c++ compiler (cxx: g++) ... no
checking for the c++ compiler (cxx: clang++) ... no
error: ...mdir\core\sandbox\modules\import\core\base\scheduler.lua:47: cannot get program for cxx
stack traceback:
	[C]: in function 'error'
	@programdir\core\base\os.lua:787: in function 'raise'
	...mdir\core\sandbox\modules\import\core\base\scheduler.lua:47: in function 'co_start_named'
	@programdir\modules\private\async\runjobs.lua:185: in function <@programdir\modules\private\async\runjobs.lua:144>
	[C]: in function 'trycall'
	@programdir\core\base\scheduler.lua:423: in function 'co_group_begin'
	...mdir\core\sandbox\modules\import\core\base\scheduler.lua:85: in function 'co_group_begin'
	@programdir\modules\private\async\runjobs.lua:144: in function 'runjobs'
	@programdir\actions\build\build.lua:221: in function 'build'
	@programdir\actions\build\main.lua:116: in function <@programdir\actions\build\main.lua:111>
	[C]: in function 'trycall'
	@programdir\core\sandbox\modules\try.lua:121: in function 'try'
	@programdir\actions\build\main.lua:110: in function <@programdir\actions\build\main.lua:83>
	[C]: in function 'load'
	@programdir\core\base\task.lua:520: in function 'run'
	@programdir\core\main.lua:259: in function 'cotask'
	@programdir\core\base\scheduler.lua:317: in function <@programdir\core\base\scheduler.lua:315>

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:xmakeBuildForArmv7'.
> exec failed( -1)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
2 actionable tasks: 2 executed

**Comment by waruqi** [comment]
见：https://github.com/xmake-io/xmake-gradle/issues/2#issuecomment-616978148

配置下ndk路径

**Comment by waruqi** [comment]
或者更新到 1.1.0 ，我改进了ndk探测，可以从as/gradle properties中检测到ndk配置

**Comment by hsav20** [comment]
04-27 10:10:53.786 2574-2574/ltd.hsav E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ltd.hsav, PID: 2574
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/ltd.hsav-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]] couldn't find "libnative-lib.so"
        at java.lang.Runtime.loadLibrary(Runtime.java:366)
        at java.lang.System.loadLibrary(System.java:988)
        at ltd.hsav.MainActivity.<clinit>(MainActivity.java:12)
        at java.lang.reflect.Constructor.newInstance(Native Method)
        at java.lang.Class.newInstance(Class.java:1606)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1066)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2226)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
        at android.app.ActivityThread.access$800(ActivityThread.java:151)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
04-27 10:10:53.790 469-483/? W/ActivityManager:   Force finishing activity 1 ltd.hsav/.MainActivity
04-27 10:10:53.814 469-1840/? I/OpenGLRenderer: Initialized EGL, version 1.4
04-27 10:10:53.815 469-1840/? E/EGL_adreno: CreateContext rcMajorVersion:3, minorVersion:0
04-27 10:10:53.815 469-1840/? D/EGL_adreno: eglCreateContext: 0xaebf15e0: maj 3 min 0 rcv 3
04-27 10:10:54.291 469-505/? W/ActivityManager: Activity pause timeout for ActivityRecord{164956d6 u0 ltd.hsav/.MainActivity t3290 f}
04-27 10:10:54.867 723-973/? W/OpenGLRenderer: Incorrectly called buildLayer on View: lo, destroying layer...
04-27 10:10:55.295 577-577/? W/ResourceType: No package identifier when getting value for resource number 0x00000000
04-27 10:10:55.295 577-577/? W/PackageManager: Failure retrieving resources for ltd.hsav: Resource ID #0x0
04-27 10:10:56.341 469-1045/? W/ActivityManager: getTasks: caller 10009 does not hold REAL_GET_TASKS; limiting output
04-27 10:10:56.461 469-543/? E/WifiStateMachine: WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=-0.00 rxSuccessRate=-0.00 targetRoamBSSID=any RSSI=-55
04-27 10:11:01.344 469-2188/? W/ActivityManager: getTasks: caller 10009 does not hold REAL_GET_TASKS; limiting output
04-27 10:11:04.394 469-505/? W/ActivityManager: Activity destroy timeout for ActivityRecord{164956d6 u0 ltd.hsav/.MainActivity t3290 f}
04-27 10:11:06.350 469-1045/? W/ActivityManager: getTasks: caller 10009 does not hold REAL_GET_TASKS; limiting output
04-27 10:11:07.395 469-560/? D/TaskPersister: removeObsoleteFile: deleting file=3290_task.xml

**Comment by hsav20** [comment]
现在提示找不到so文件了，怎样放都不行

**Comment by hsav20** [comment]
Executing tasks: [:app:assembleDebug] in project D:\ktv\changba\TestC


> Configure project :
Repository https://jcenter.bintray.com/ replaced by http://maven.aliyun.com/nexus/content/groups/public.
Repository https://jcenter.bintray.com/ replaced by http://maven.aliyun.com/nexus/content/groups/public.

> Configure project :app
[xmake/plugin]: activated for project: app

> Task :app:xmakeConfigureForArm64
>> xmake f -y -v -p android -a arm64-v8a --ndk=E:\Android\sdk\ndk\21.0.6113669 --buildir=D:\ktv\changba\TestC\app\build\xmake 
checking for the NDK directory ... E:\Android\sdk\ndk\21.0.6113669
checking for the SDK version of NDK ... 21
checking for the toolchains version of NDK ... 4.9
checking for the Android SDK directory ... E:\Android\sdk
checking for the Build Tools Version of Android SDK ... 28.0.3
checking for the aarch64-linux-android-g++ ... no
checking for the linker (ld: g++) ... no
checking for the aarch64-linux-android-gcc ... no
checking for the linker (ld: gcc) ... no
checking for the clang++ ... E:\Android\sdk\ndk\21.0.6113669\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++
checking for the linker (ld) ... clang++
checking for the shared library linker (sh: g++) ... no
checking for the shared library linker (sh: gcc) ... no
checking for the shared library linker (sh) ... clang++
configure
{
    ld = E:\Android\sdk\ndk\21.0.6113669\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++
    ndk = E:\Android\sdk\ndk\21.0.6113669
    ndk_stdcxx = true
    host = windows
    sdk = E:\Android\sdk
    buildir = ..\..\..\build\xmake
    ndk_toolchains_ver = 4.9
    ndk_sdkver = 21
    arch = arm64-v8a
    ccache = true
    build_toolver = 28.0.3
    mode = release
    plat = android
    bin = E:\Android\sdk\ndk\21.0.6113669\toolchains\llvm\prebuilt\windows-x86_64\bin
    cross = aarch64-linux-android-
    sh = E:\Android\sdk\ndk\21.0.6113669\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++
    kind = static
    gcc_toolchain = E:\Android\sdk\ndk\21.0.6113669\toolchains\aarch64-linux-android-4.9\prebuilt\windows-x86_64
    android_sdk = E:\Android\sdk
    ndkver = 21
}

> Task :app:xmakeBuildForArm64
>> xmake build -v 
configure
{
    sh = E:\Android\sdk\ndk\21.0.6113669\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++
    ndk = E:\Android\sdk\ndk\21.0.6113669
    ndk_stdcxx = true
    host = windows
    sdk = E:\Android\sdk
    buildir = ..\..\..\build\xmake
    ndk_toolchains_ver = 4.9
    ndk_sdkver = 21
    arch = arm64-v8a
    ccache = true
    build_toolver = 28.0.3
    mode = release
    cross = aarch64-linux-android-
    bin = E:\Android\sdk\ndk\21.0.6113669\toolchains\llvm\prebuilt\windows-x86_64\bin
    plat = android
    kind = static
    gcc_toolchain = E:\Android\sdk\ndk\21.0.6113669\toolchains\aarch64-linux-android-4.9\prebuilt\windows-x86_64
    android_sdk = E:\Android\sdk
    ld = E:\Android\sdk\ndk\21.0.6113669\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++
    ndkver = 21
}
checking for the c++ compiler (cxx: g++) ... no
checking for the c++ compiler (cxx) ... clang++
checking for the E:\Android\sdk\ndk\21.0.6113669\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++ ... ok
checking for the flags (-Oz) ... ok
[100%]: build ok!
configure
{
    sh = E:\Android\sdk\ndk\21.0.6113669\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++
    ndk = E:\Android\sdk\ndk\21.0.6113669
    ndk_stdcxx = true
    host = windows
    sdk = E:\Android\sdk
    buildir = ..\..\..\build\xmake
    ndk_toolchains_ver = 4.9
    ndk_sdkver = 21
    arch = arm64-v8a
    plat = android
    build_toolver = 28.0.3
    mode = release
    gcc_toolchain = E:\Android\sdk\ndk\21.0.6113669\toolchains\aarch64-linux-android-4.9\prebuilt\windows-x86_64
    cxx = E:\Android\sdk\ndk\21.0.6113669\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++
    bin = E:\Android\sdk\ndk\21.0.6113669\toolchains\llvm\prebuilt\windows-x86_64\bin
    cross = aarch64-linux-android-
    kind = static
    ld = E:\Android\sdk\ndk\21.0.6113669\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++
    android_sdk = E:\Android\sdk
    ccache = true
    ndkver = 21
}
installing nativelib ...
installing to D:\ktv\changba\TestC\app\build\xmake\libs\arm64-v8a ...
> copy ..\..\..\build\xmake\android\arm64-v8a\release\libnativelib.so to D:\ktv\changba\TestC\app\build\xmake\libs\arm64-v8a\lib ..
install ok!

> Task :app:xmakeConfigureForArmv7
>> xmake f -y -v -p android -a armeabi-v7a --ndk=E:\Android\sdk\ndk\21.0.6113669 --buildir=D:\ktv\changba\TestC\app\build\xmake 
checking for the NDK directory ... E:\Android\sdk\ndk\21.0.6113669
checking for the SDK version of NDK ... 21
checking for the toolchains version of NDK ... 4.9
checking for the Android SDK directory ... E:\Android\sdk
checking for the Build Tools Version of Android SDK ... 28.0.3
checking for the arm-linux-androideabi-g++ ... no
checking for the linker (ld: g++) ... no
checking for the arm-linux-androideabi-gcc ... no
checking for the linker (ld: gcc) ... no
checking for the clang++ ... E:\Android\sdk\ndk\21.0.6113669\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++
checking for the linker (ld) ... clang++
checking for the shared library linker (sh: g++) ... no
checking for the shared library linker (sh: gcc) ... no
checking for the shared library linker (sh) ... clang++
configure
{
    ld = E:\Android\sdk\ndk\21.0.6113669\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++
    ndk = E:\Android\sdk\ndk\21.0.6113669
    ndk_stdcxx = true
    host = windows
    sdk = E:\Android\sdk
    buildir = ..\..\..\build\xmake
    ndk_toolchains_ver = 4.9
    ndk_sdkver = 21
    arch = armeabi-v7a
    ccache = true
    build_toolver = 28.0.3
    mode = release
    plat = android
    bin = E:\Android\sdk\ndk\21.0.6113669\toolchains\llvm\prebuilt\windows-x86_64\bin
    cross = arm-linux-androideabi-
    sh = E:\Android\sdk\ndk\21.0.6113669\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++
    kind = static
    gcc_toolchain = E:\Android\sdk\ndk\21.0.6113669\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64
    android_sdk = E:\Android\sdk
    ndkver = 21
}

> Task :app:xmakeBuildForArmv7
>> xmake build -v 
configure
{
    sh = E:\Android\sdk\ndk\21.0.6113669\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++
    ndk = E:\Android\sdk\ndk\21.0.6113669
    ndk_stdcxx = true
    host = windows
    sdk = E:\Android\sdk
    buildir = ..\..\..\build\xmake
    ndk_toolchains_ver = 4.9
    ndk_sdkver = 21
    arch = armeabi-v7a
    ccache = true
    build_toolver = 28.0.3
    mode = release
    cross = arm-linux-androideabi-
    bin = E:\Android\sdk\ndk\21.0.6113669\toolchains\llvm\prebuilt\windows-x86_64\bin
    plat = android
    kind = static
    gcc_toolchain = E:\Android\sdk\ndk\21.0.6113669\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64
    android_sdk = E:\Android\sdk
    ld = E:\Android\sdk\ndk\21.0.6113669\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++
    ndkver = 21
}
checking for the c++ compiler (cxx: g++) ... no
checking for the c++ compiler (cxx) ... clang++
checking for the E:\Android\sdk\ndk\21.0.6113669\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++ ... ok
checking for the flags (-Oz) ... ok
[100%]: build ok!
configure
{
    sh = E:\Android\sdk\ndk\21.0.6113669\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++
    ndk = E:\Android\sdk\ndk\21.0.6113669
    ndk_stdcxx = true
    host = windows
    sdk = E:\Android\sdk
    buildir = ..\..\..\build\xmake
    ndk_toolchains_ver = 4.9
    ndk_sdkver = 21
    arch = armeabi-v7a
    plat = android
    build_toolver = 28.0.3
    mode = release
    gcc_toolchain = E:\Android\sdk\ndk\21.0.6113669\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64
    cxx = E:\Android\sdk\ndk\21.0.6113669\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++
    bin = E:\Android\sdk\ndk\21.0.6113669\toolchains\llvm\prebuilt\windows-x86_64\bin
    cross = arm-linux-androideabi-
    kind = static
    ld = E:\Android\sdk\ndk\21.0.6113669\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++
    android_sdk = E:\Android\sdk
    ccache = true
    ndkver = 21
}
installing nativelib ...
installing to D:\ktv\changba\TestC\app\build\xmake\libs\armeabi-v7a ...
> copy ..\..\..\build\xmake\android\armeabi-v7a\release\libnativelib.so to D:\ktv\changba\TestC\app\build\xmake\libs\armeabi-v7a\lib ..
install ok!

> Task :app:xmakeConfigureForX86
>> xmake f -y -v -p android -a x86 --ndk=E:\Android\sdk\ndk\21.0.6113669 --buildir=D:\ktv\changba\TestC\app\build\xmake 
checking for the NDK directory ... E:\Android\sdk\ndk\21.0.6113669
checking for the SDK version of NDK ... 21
checking for the toolchains version of NDK ... 4.9
checking for the Android SDK directory ... E:\Android\sdk
checking for the Build Tools Version of Android SDK ... 28.0.3
checking for the i686-linux-android-g++ ... no
checking for the linker (ld: g++) ... no
checking for the i686-linux-android-gcc ... no
checking for the linker (ld: gcc) ... no
checking for the clang++ ... E:\Android\sdk\ndk\21.0.6113669\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++
checking for the linker (ld) ... clang++
checking for the shared library linker (sh: g++) ... no
checking for the shared library linker (sh: gcc) ... no
checking for the shared library linker (sh) ... clang++
configure
{
    ld = E:\Android\sdk\ndk\21.0.6113669\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++
    ndk = E:\Android\sdk\ndk\21.0.6113669
    ndk_stdcxx = true
    host = windows
    sdk = E:\Android\sdk
    buildir = ..\..\..\build\xmake
    ndk_toolchains_ver = 4.9
    ndk_sdkver = 21
    arch = x86
    ccache = true
    build_toolver = 28.0.3
    mode = release
    plat = android
    bin = E:\Android\sdk\ndk\21.0.6113669\toolchains\llvm\prebuilt\windows-x86_64\bin
    cross = i686-linux-android-
    sh = E:\Android\sdk\ndk\21.0.6113669\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++
    kind = static
    gcc_toolchain = E:\Android\sdk\ndk\21.0.6113669\toolchains\x86-4.9\prebuilt\windows-x86_64
    android_sdk = E:\Android\sdk
    ndkver = 21
}

> Task :app:xmakeBuildForX86
>> xmake build -v 
configure
{
    sh = E:\Android\sdk\ndk\21.0.6113669\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++
    ndk = E:\Android\sdk\ndk\21.0.6113669
    ndk_stdcxx = true
    host = windows
    sdk = E:\Android\sdk
    buildir = ..\..\..\build\xmake
    ndk_toolchains_ver = 4.9
    ndk_sdkver = 21
    arch = x86
    ccache = true
    build_toolver = 28.0.3
    mode = release
    cross = i686-linux-android-
    bin = E:\Android\sdk\ndk\21.0.6113669\toolchains\llvm\prebuilt\windows-x86_64\bin
    plat = android
    kind = static
    gcc_toolchain = E:\Android\sdk\ndk\21.0.6113669\toolchains\x86-4.9\prebuilt\windows-x86_64
    android_sdk = E:\Android\sdk
    ld = E:\Android\sdk\ndk\21.0.6113669\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++
    ndkver = 21
}
checking for the c++ compiler (cxx: g++) ... no
checking for the c++ compiler (cxx) ... clang++
checking for the E:\Android\sdk\ndk\21.0.6113669\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++ ... ok
checking for the flags (-Oz) ... ok
[100%]: build ok!
configure
{
    sh = E:\Android\sdk\ndk\21.0.6113669\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++
    ndk = E:\Android\sdk\ndk\21.0.6113669
    ndk_stdcxx = true
    host = windows
    sdk = E:\Android\sdk
    buildir = ..\..\..\build\xmake
    ndk_toolchains_ver = 4.9
    ndk_sdkver = 21
    arch = x86
    plat = android
    build_toolver = 28.0.3
    mode = release
    gcc_toolchain = E:\Android\sdk\ndk\21.0.6113669\toolchains\x86-4.9\prebuilt\windows-x86_64
    cxx = E:\Android\sdk\ndk\21.0.6113669\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++
    bin = E:\Android\sdk\ndk\21.0.6113669\toolchains\llvm\prebuilt\windows-x86_64\bin
    cross = i686-linux-android-
    kind = static
    ld = E:\Android\sdk\ndk\21.0.6113669\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++
    android_sdk = E:\Android\sdk
    ccache = true
    ndkver = 21
}
installing nativelib ...
installing to D:\ktv\changba\TestC\app\build\xmake\libs\x86 ...
> copy ..\..\..\build\xmake\android\x86\release\libnativelib.so to D:\ktv\changba\TestC\app\build\xmake\libs\x86\lib ..
install ok!

> Task :app:xmakeBuild

> Task :app:xmakeInstall
>> install artifacts to D:\ktv\changba\TestC\app\libs
running given lua script file ..\..\..\build\xmake\install_artifacts.lua with args:
  - "D:\ktv\changba\TestC\app\build\xmake\libs"
  - "D:\ktv\changba\TestC\app\libs"
  - "armeabi-v7a,arm64-v8a,x86"
> copy D:\ktv\changba\TestC\app\build\xmake\libs\armeabi-v7a\lib\libnativelib.so to D:\ktv\changba\TestC\app\libs\armeabi-v7a ..
> copy D:\ktv\changba\TestC\app\build\xmake\libs\arm64-v8a\lib\libnativelib.so to D:\ktv\changba\TestC\app\libs\arm64-v8a ..
> copy D:\ktv\changba\TestC\app\build\xmake\libs\x86\lib\libnativelib.so to D:\ktv\changba\TestC\app\libs\x86 ..

> Task :app:preBuild
> Task :app:preDebugBuild
> Task :app:compileDebugAidl NO-SOURCE
> Task :app:generateDebugBuildConfig UP-TO-DATE
> Task :app:compileDebugRenderscript NO-SOURCE
> Task :app:javaPreCompileDebug UP-TO-DATE
> Task :app:mainApkListPersistenceDebug UP-TO-DATE
> Task :app:generateDebugResValues UP-TO-DATE
> Task :app:generateDebugResources UP-TO-DATE
> Task :app:mergeDebugResources UP-TO-DATE
> Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
> Task :app:extractDeepLinksDebug UP-TO-DATE
> Task :app:processDebugManifest UP-TO-DATE
> Task :app:processDebugResources UP-TO-DATE
> Task :app:compileDebugJavaWithJavac UP-TO-DATE
> Task :app:compileDebugSources UP-TO-DATE
> Task :app:mergeDebugShaders UP-TO-DATE
> Task :app:compileDebugShaders UP-TO-DATE
> Task :app:generateDebugAssets UP-TO-DATE
> Task :app:mergeDebugAssets UP-TO-DATE
> Task :app:processDebugJavaRes NO-SOURCE
> Task :app:mergeDebugJavaResource UP-TO-DATE
> Task :app:dexBuilderDebug UP-TO-DATE
> Task :app:checkDebugDuplicateClasses UP-TO-DATE
> Task :app:mergeExtDexDebug UP-TO-DATE
> Task :app:mergeDexDebug UP-TO-DATE
> Task :app:mergeDebugJniLibFolders
> Task :app:mergeDebugNativeLibs UP-TO-DATE
> Task :app:stripDebugDebugSymbols UP-TO-DATE
> Task :app:validateSigningDebug UP-TO-DATE
> Task :app:packageDebug UP-TO-DATE
> Task :app:assembleDebug UP-TO-DATE

BUILD SUCCESSFUL in 8s
31 actionable tasks: 9 executed, 22 up-to-date

**Comment by waruqi** [comment]
> copy D:\ktv\changba\TestC\app\build\xmake\libs\armeabi-v7a\lib\libnativelib.so to D:\ktv\changba\TestC\app\libs\armeabi-v7a ..

仔细看log，你xmake.lua里面编译生成的是 libnativelib.so，而你loadlibrary的是libnative-lib.so，库名字都不同。。。。

> java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/ltd.hsav-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]] couldn't find "libnative-lib.so"

**Comment by hsav20** [comment]
是的，我错了。另外建议你用cmake生成的例子用到的名字及位置，这样入门简单点
